### PR TITLE
Location bug

### PR DESCRIPTION
**Pull request by snoopyjoe**
Fix default save location bug

### CODE REVIEW

**Comment by DiR3Wolf** [comment]
@snoopyjoe would it be a better idea, instead of copying and duplicating the files, for the "save Location" of all those files to move to the target folder? So default would be psvue userdata location, otherwise, whatever the target folder specified in settings.

**Comment by eracknaphobia** [comment]
@DiR3Wolf  I think that was the initial problem I ran into as well. There seems to be a permissions restraint that wouldn't allow the service to write directly to the share. So the work around is to copy with xbmcvfs.

@snoopyjoe I still think there is an issue as the save locations and copy locations don't "match" so it overwrites still. Maybe we should just use a boolean and not bother comparing path names until the boolean is enabled?

```
14:02:31.340 T:22800   DEBUG: copy location C:\Users\egates\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.psvue
14:02:31.340 T:22800   DEBUG: save location C:\Users\egates\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.psvue\
```

**Comment by snoopyjoe** [comment]
@eracknaphobia wow one backslash is always the culprit lol. I'll make a bool setting that will enable or disable the custom directory, then add that bool to the copy condition. It should only copy of the custom directory is enabled. 

@DiR3Wolf Python only has permission to write files on the local OS it's running on. There is a python library called SMBClient which will allow python read/write access to smb shares but I couldn't find a Kodi module for it. Also I'm not sure how it would handle other shares like nfs and afp. The xbmcvfs was the only work around I could find.

**Comment by DiR3Wolf** [comment]
@snoopyjoe @eracknaphobia Thanks. That makes sense. Keep up the good work guys!!!

**Comment by snoopyjoe** [comment]
Ok so last commit should be the correct fix. Bool setting for custom directory is bug proof!

**Comment by eracknaphobia** [comment]
Hahaha, thanks.

**Pull request merged**
